openapi: 3.1.0
info:
  title: Inditex Code Challenge
  description: |-
    API definition for the code challenge for Tech Lead in Inditex.

  contact:
    email: alvaroberrocal12@gmail.com
  version: 1.0.1
servers:
  - url: https://localhost:8080/api/
tags:
  - name: prices
    description: Prices API
paths:
  /pet:
    get:
      tags:
        - prices
      summary: Find the applied price filter
      description: Multiple status values can be provided with comma separated strings
      operationId: findPricesByFilters
      parameters:
        - name: applicationDate
          in: query
          description: Applicable price date
          required: true
          schema:
            type: string
            format: date-time
        - name: productId
          in: query
          description: Product Id
          required: true
          schema:
            type: string
            format: date-time
        - name: brandId
          in: query
          description: Brand Id
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ProductPrice'
        '404':
          description: Not found
        '400':
          description: Bad Request
components:
  schemas:
    ProductPrice:
      required:
        - product_id
        - brand_id
        - price_list
        - start_date
        - end_date
        - pvp
      type: object
      properties:
        product_id:
          type: integer
          format: int64
          example: 10
        brand_id:
          type: integer
          format: int64
          example: 1
        price_list:
          type: integer
          format: int32
          example: 1
        start_date:
          type: string
          format: date-time
          example: 2023-01-21T17:32:28Z
        end_date:
          type: string
          format: date-time
          example: 2023-05-21T17:32:28Z
        pvp:
          type: integer
          format: int32
          example: 10.95

